---
title: A Night In Japan
timezone: UTC
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: jordelquino@gmail.com
description: A blog about Japan
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
